name: Githubactions demo

on: 
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "testing...."

  Test-Load:
    runs-on: ubuntu-latest
    if: github.event_name == "workflow_dispatch"
    needs: Build
    environment: Load-Test
    steps:
      - run: |
        echo "running tests..."
        sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Test-Load]
    environment:
      name: Production
      url: https://github.com/Yahkem/TuringMachineVYSL1
    steps:
      - run: echo "deploying to prod.."
  
